version: '3'
services:
      mysql:
            image: mysql:latest
            container_name: mysql
            environment:
                  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
                  MYSQL_DATABASE: mysql_myagizmaktav
                  
            ports:
                  - 3306:3306
            volumes:
                  - db_data:/var/lib/mysql
            command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_turkish_ci
            restart: always
            networks:
                  - db-net
      node:
            image: node:latest
            container_name: node
            build: 
                  context: .
                  dockerfile: Dockerfile
            volumes:
                  - ./:/usr/src/app
            working_dir: /usr/src/app
            ports:
                  - 3000:3000
            command: npm start
            depends_on:
                  - mysql
            networks:
                  - db-net
volumes:
      db_data: {}
networks:
      db-net:
            driver: bridge
